timezone: UTC
latency_targets_ms:
  ingest: 100
  processing: 250
  execution: 75
data_paths:
  raw: ./data
  features: ./data/features
  logs: ./logs
sessions:
  london: { start: "07:00", end: "16:00" }
  new_york: { start: "12:00", end: "21:00" }
llm_model_path: ./models/llm/model.gguf
