news:
  provider: newsapi
  api_key_env: NEWS_API_KEY
  rate_limit_per_minute: 30
social:
  reddit:
    enabled: true
    client_id_env: REDDIT_CLIENT_ID
    client_secret_env: REDDIT_CLIENT_SECRET
  twitter:
    enabled: false
    bearer_token_env: TWITTER_BEARER_TOKEN
research:
  arxiv: true
  github: true
cache:
  dir: data/web_cache
  ttl_minutes: 1440
