name: CI

on:
  push:
    branches: [main, work]
  pull_request:
    branches: [main, work]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff check src tests
          mypy src
      - name: Tests
        run: pytest
      - name: Build docker image
        run: docker build . -t ai-scalper-god:ci
